<a href="https://colab.research.google.com/github/vikrampal12345/Practice_Revision_Machine_learning/blob/main/2_OneHotEncoder_mushroom_dataset_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [32]:
df = pd.read_csv("/content/mushrooms.csv")
df.shape

(8124, 23)

In [33]:
df.isnull().sum()  # no null

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [34]:
df.info()    # all data is in object type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring    8124 non-null   object
 15  stalk-color-below-ring    8124 non-null   object
 16  veil-type                 8124 non-null   object
 17  veil-color                8124 non-null   object
 18  ring-number               8124 non-null   object
 19  ring-type                 8124 non-null   object
 20  spore-print-color         8124 non-null   object
 21  population                8124 non-null   object
 22  habitat                   8124 non-null   object
dtypes: object(23)
memory usage: 1.4+ MB

In [35]:
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [36]:
df['class'].value_counts()

class
e    4208
p    3916
Name: count, dtype: int64

In [37]:
pd.crosstab(df['habitat'], df['class'])

class       e     p
habitat
d        1880  1268
g        1408   740
l         240   592
m         256    36
p         136  1008
u          96   272
w         192     0

In [38]:
pd.crosstab(df['cap-shape'], df['class'])

class         e     p
cap-shape
b           404    48
c             0     4
f          1596  1556
k           228   600
s            32     0
x          1948  1708

In [39]:
pd.crosstab(df['cap-color'], df['class'])

class         e     p
cap-color
b            48   120
c            32    12
e           624   876
g          1032   808
n          1264  1020
p            56    88
r            16     0
u            16     0
w           720   320
y           400   672

In [40]:
pd.crosstab(df['population'], df['class'])

class          e     p
population
a            384     0
c            288    52
n            400     0
s            880   368
v           1192  2848
y           1064   648

In [41]:
pd.crosstab(df['ring-type'], df['class'])

class         e     p
ring-type
e          1008  1768
f            48     0
l             0  1296
n             0    36
p          3152   816

In [42]:
x = df.drop(columns='class')
y = df.iloc[:,0]

X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape

((6499, 22), (1625, 22), (6499,))

In [43]:
print(type(x))
print(type(X_train))
print(type(X_test))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [44]:
X_train

,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
7873,k,s,e,f,s,f,c,n,b,t,...,k,p,w,p,w,o,e,w,v,d
6515,x,s,n,f,f,f,c,n,b,t,...,s,w,w,p,w,o,e,w,v,p
6141,f,y,e,f,y,f,c,n,b,t,...,s,p,w,p,w,o,e,w,v,l
2764,f,f,n,t,n,f,c,b,u,t,...,s,g,p,p,w,o,p,n,v,d
438,b,y,y,t,l,f,c,b,k,e,...,s,w,w,p,w,o,p,n,n,m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,x,y,n,f,f,f,c,n,b,t,...,s,p,w,p,w,o,e,w,v,p
5390,k,y,e,t,n,f,c,b,w,e,...,s,w,e,p,w,t,e,w,c,w
860,f,y,n,t,l,f,c,b,w,e,...,y,w,w,p,w,o,p,n,y,p
7603,k,s,e,f,f,f,c,n,b,t,...,s,p,p,p,w,o,e,w,v,p
7270,k,f,g,f,n,f,w,b,g,e,...,k,w,w,p,w,t,p,w,n,g

In [45]:
type(X_train)

pandas.core.frame.DataFrame

In [46]:
ohe = OneHotEncoder(sparse_output = False, drop='first')

X_train_new = ohe.fit_transform(X_train)
X_test_new = ohe.transform(X_test)

In [47]:
lb = LabelEncoder( )

y_train_new = lb.fit_transform(y_train)
y_test_new = lb.transform(y_test)

In [48]:
lg = LogisticRegression()

lg.fit(X_train_new, y_train_new)

y_pred = lg.predict(X_test_new)

accuracy_score(y_test_new, y_pred)

1.0

In [49]:
from sklearn.model_selection import cross_val_score
lg = LogisticRegression()
scores = cross_val_score(lg, X_train_new, y_train_new, cv=5)

print(scores)
print(scores.mean())

[0.99923077 1.         1.         1.         0.99846035]
0.9995382246698643